-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzwaq/prx+LbbrOEnnVZpt/GbN8x0hFYcRdII/JYCwOmgCgYIKoZIzj0DAQehRANCAATeKa+PajeRG40e6JNS8vDWnNpqhq7gU9YDhiWoPT0oZiS4D7kFL3p/dwYZm5D/LZXkEbdhCRnTa6ybl2LwsBT8
-----END PRIVATE KEY-----